# Generated by Django 6.0 on 2026-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimLiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('INVESTIGATE', 'Investigate'), ('BLOCKED', 'Blocked')], max_length=20)),
            ],
        ),
    ]
