# Generated by Django 6.0.4 on 2026-04-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seimLiteApp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='seimLiteApp.project'),
            preserve_default=False,
        ),
    ]
